config/routes.rb
Rails.application.routes.draw do

 
  root 'products#index'
  get 'home/index', to: 'home#index'
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  resources :orders, :line_items, :carts, :coupons, :addresses, :wishlists

  post 'check_coupon_code', to: 'coupons#check_coupon_code'
  delete 'remove_coupon', to: 'coupons#remove_coupon'
  delete 'remove_from_wishlist', to: 'wishlists#remove_from_wishlist'
  delete 'remove_product_from_order', to: 'orders#remove_product_from_order'
  get 'get_deleted_products', to: 'orders#get_deleted_products'


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :products, only: [:index, :show]
  #   resources :product_images
  # end
  resources :categories, only: [:show]
  resources :webhooks, only: [:create]
  resources :charges, only: [:new, :create]
  resources :paypals, only: [:new, :create]
  resources :track_orders,only: [:new, :create, :show]
  resources :contacts, only: [:index, :create]
  resources :refunds


  resources :newsletters, only: [:index, :create, :destroy]
  get '/newsletters/subscribe', to: 'newsletters#subscribe'
  get '/newsletters/unsubscribe', to: 'newsletters#unsubscribe'

end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_action :set_newsletter, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /newsletters or /newsletters.json
  def index
    @newsletters = Newsletter.all
    @newsletter = Newsletter.new
    @categories = Category.all
    @subscription_type = ['Daily', 'Weekly']
  end

  # GET /newsletters/1 or /newsletters/1.json
  def show
  end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
  end

  # GET /newsletters/1/edit
  def edit
  end

  # POST /newsletters or /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params)

    respond_to do |format|
      if @newsletter.save
        NewsletterNotifierMailer.send_subscribed_email(@newsletter).deliver

        format.html { redirect_to newsletters_url, notice: "Please Check Your Email And Confirm!" }
        format.json { render :show, status: :created, location: @newsletter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1 or /newsletters/1.json
  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to newsletter_url(@newsletter), notice: "Newsletter was successfully updated." }
        format.json { render :show, status: :ok, location: @newsletter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  def subscribe
    if params.include? "email"
      @newsletter_user = Newsletter.where(email: params[:email]).first
      
      if @newsletter_user.confirmed_at.nil?
        @newsletter_user.confirmed_at = Time.now
        @newsletter_user.save!
        flash[:notice]='Your Subscription To Newsletter Is Confirmed!'
        redirect_to root_url
      else
        flash[:notice]='You are Already Subscribed to Newsletter!'
        redirect_to newsletters_url
      end
    else
      flash[:notice]='Email Id Is Missing!'
      redirect_to root_url
    end

  end

  def unsubscribe
    if params.include? "email"
      @newsletter_user = Newsletter.where(email: params[:email]).first
      
      unless @newsletter_user.confirmed_at.nil?
        @newsletter_user.confirmed_at = nil
        @newsletter_user.save!
        flash[:notice]='You Have Unsubscribed To Newsletter!'
        redirect_to root_url
      else
        flash[:notice]='You are Already Unsubscribed to Newsletter!'
        redirect_to newsletters_url
      end
    else
      flash[:notice]='Email Id Is Missing!'
      redirect_to root_url
    end

  end

  # DELETE /newsletters/1 or /newsletters/1.json
  def destroy
    @newsletter.destroy

    respond_to do |format|
      format.html { redirect_to newsletters_url, notice: "Newsletter was successfully unsubscribed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def newsletter_params
      params.require(:newsletter).permit(:email, :subscription_type, categories:[])
    end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/newsletters/_form.html.erb
<%= form_with(model: newsletter) do |form| %>
  <% if newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
        <% newsletter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/newsletters/edit.html.erb
<h1>Editing Newsletter</h1>

<%= render 'form', newsletter: @newsletter %>

<%= link_to 'Show', @newsletter %> |
<%= link_to 'Back', newsletters_path %>

app/views/newsletters/index.html.erb
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-4">
                <div class="card">
                    <div class="card-header text-center">
                        <h1>Newsletters</h1>
                    </div>
                    <div class="card-body">
                        <div class="my-5">
                            <%= form_with(model: @newsletter) do |f| %>
                                <div class="form-floating"><h4>Email:</h4>
                                    <div class="form-group">
                                        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
                                    </div>
                                </div><br>
                                <div class="form-floating"><h4>Categories:</h4>
                                    <div class="form-group">
                                      <p><% @categories.each do |category|  %>
                                      <span><%= f.check_box :categories, {multiple: true}, category.id, false %></span> 
                                        <%= f.label category.name %>
                                      <% end %><p>
                                    </div>                              
                                </div>                             
                                 <div class="form-floating"><h4>Plan:</h4>
                                    <div class="form-group">
                                      <% @subscription_type.each do |subscribe|  %>
                                        <%= f.radio_button :subscription_type, subscribe %>
                                        <%= f.label subscribe %>
                                      <% end %>
                                    </div>                              
                                </div>
                                <div class="actions">
                                    <%= f.submit "Subscribe",class: "btn btn-outline-info" %>
                                </div>
                            <% end %>                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

app/views/newsletters/new.html.erb
<h1>New Newsletter</h1>

<%= render 'form', newsletter: @newsletter %>

<%= link_to 'Back', newsletters_path %>

app/views/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @newsletter.email %>
</p>

<%= link_to 'Edit', edit_newsletter_path(@newsletter) %> |
<%= link_to 'Back', newsletters_path %>