config/routes.rb
Rails.application.routes.draw do

 
  root 'products#index'
  get 'home/index', to: 'home#index'
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  resources :orders, :line_items, :carts, :coupons, :addresses, :wishlists

  post 'check_coupon_code', to: 'coupons#check_coupon_code'
  delete 'remove_coupon', to: 'coupons#remove_coupon'
  delete 'remove_from_wishlist', to: 'wishlists#remove_from_wishlist'
  delete 'remove_product_from_order', to: 'orders#remove_product_from_order'
  get 'get_deleted_products', to: 'orders#get_deleted_products'


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :products, only: [:index, :show]
  #   resources :product_images
  # end
  resources :categories, only: [:show]
  resources :webhooks, only: [:create]
  resources :charges, only: [:new, :create]
  resources :paypals, only: [:new, :create]
  resources :track_orders,only: [:new, :create, :show]
  resources :contacts, only: [:index, :create]
  resources :refunds


  resources :newsletters, only: [:index, :create, :destroy]
  get '/newsletters/subscribe', to: 'newsletters#subscribe'
  get '/newsletters/unsubscribe', to: 'newsletters#unsubscribe'

end

app/models/address.rb
class Address < ApplicationRecord
    has_one :order
    belongs_to :user

    validates :address_1, :address_2, :city, :state, :country, :zipcode, :user_id, presence: true
end

app/models/banner_image.rb
class BannerImage < ApplicationRecord
    has_one_attached :image
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_product(product_id)
        current_item = line_items.find_by(product_id: product_id)
        if current_item
            current_item.quantity += 1
        else
            current_item = line_items.build(product_id: product_id)
        end
        current_item
    end

    def total
        line_items.to_a.sum {|item| item.total}
    end

end

app/models/category.rb
class Category < ApplicationRecord
    has_and_belongs_to_many :products, dependent: :delete_all
end

app/models/cm.rb
class Cm < ApplicationRecord
    has_rich_text :content
end

app/models/configuration.rb
class Configuration < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord

    validates :name, :contact_no, :email, :message,  presence: true
    after_create_commit :send_admin_notification
    after_update :send_user_notification

    def send_admin_notification
        ContactAdminNotifierMailer.admin_contact_notification(email, name, contact_no, message).deliver
    end

    def send_user_notification
        ContactUserNotifierMailer.user_contact_notification(email, name, contact_no, message, admin_note).deliver
    end

end

app/models/coupon.rb
class Coupon < ApplicationRecord
    belongs_to :order, optional: true
    has_many :coupon_useds
    validates :code, uniqueness: true
end

app/models/coupon_used.rb
class CouponUsed < ApplicationRecord
  belongs_to :coupon, optional: true
  belongs_to :user, optional: true
  belongs_to :order, optional: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  before_save :set_total
  before_save :set_unit_price
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  belongs_to :cart, optional: true

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total
    product.price * quantity
  end
   
  def subtotal
    line_items.collect{|line_item| line_item.valid? ? line_item.unit_price*line_item.quantity : 0}.sum
  end
  

  private
    def set_unit_price
      self[:unit_price] = unit_price      
    end

    def set_total
      self[:total] = total * quantity      
    end

    def set_subtotal
      self[:subtotal] = subtotal
  end
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    acts_as_paranoid

    enum status: {ordered: 0, order_processing: 1, shipped: 2, out_for_delivery: 3, cancelled: 4, delivered: 5, return_in_process: 6, return_approved: 7, pickup_expected: 8, refunded: 9}

    has_one :coupon_used
    has_one :coupon, through: :coupon_used

    # has_many :line_items, dependent: :destroy
    # has_many :products, through: :line_items
    has_many :order_details, dependent: :destroy
    has_many :refunds

    belongs_to :address, optional: true
    belongs_to :user, optional: true

    validates :address_id, presence: true
    validates :total, presence: true
    validates :pay_type, presence: true

    # after_destroy :update_refund
    # after_update :send_order_notification


    def send_order_notification
        OrderNotifierMailer.order_update_notification(id).deliver
    end

    def add_line_items_from_cart(cart)
        cart.line_items.each do |item|
            item.cart_id = nil
            line_items << item
        end
    end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    acts_as_paranoid

    enum status: {ordered: 0, order_processing: 1, shipped: 2, out_for_delivery: 3, cancelled: 4, delivered: 5, return_in_process: 6, return_approved: 7, pickup_expected: 8, refunded: 9}

    belongs_to :order, -> {with_deleted}

    after_create :send_user_order_details
        
    def send_user_order_details
        UserOrderDetailsMailer.user_order_details_notification(order_id,product_id).deliver
    end
end

app/models/product.rb
class Product < ApplicationRecord
    # acts_as_paranoid
    has_many_attached :product_images, dependent: :delete_all
    has_and_belongs_to_many :categories, dependent: :delete_all
    has_many :line_items, dependent: :delete_all
    # has_many :orders, through: :line_items, dependent: :delete_all

    before_destroy :ensure_not_referenced_by_any_line_item

    private
    #ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
        if line_items.empty?
            return true
        else
            errors.add(:base, 'Line Items present')
            return false
        end
    end
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product, optional: true
end

app/models/refund.rb
class Refund < ApplicationRecord
  belongs_to :user
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # acts_as_paranoid
  enum status: {enable: 0, disabled: 1}
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one :wishlist, dependent: :destroy
  has_many :refunds, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2, :twitter, :facebook]

  after_create :send_user_notification unless :twitter
  after_create :send_admin_notification

  def active_for_authentication?
   super && !disabled?
  end

  def inactive_message
     !disabled? ? super : :account_inactive
  end

  def send_user_notification
    UserNotifierMailer.user_creation_notification(email, password).deliver
  end

  def send_admin_notification
    UserCreateAdminNotifierMailer.user_creation_admin_notification(email).deliver
  end

  # for adding stripe customer id to user
  def to_s
    email
  end

  after_create do
    Stripe.api_key = Rails.application.credentials.dig(:stripe, :stripe_secret_key)
    customer = Stripe::Customer.create(email: email)
    update(stripe_customer_id: customer.id)
  end

  # for omni auth
  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create  do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = provider_data.info.name
    end
  end

  def email_required?
    false
  end

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
end

app/helpers/carts_helper.rb
module CartsHelper
    # def get_addresses
    #     ["A-304 Golden Park", "C-401 Diamond Tower"]
    # end

    def get_user_addresses
        addresses = Array.new
        if user_signed_in?
            current_user.addresses.each do |address|             
                addresses << ["#{address.address_1}, #{address.address_2}, #{address.city}, #{address.state}", address.id]
            end
        end
        addresses
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/shared/_banner.html.erb
<section id="slider"><!--slider-->
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center pt-5 m-5">
                <div class="carousel-inner ">
                    <div class="carousel-item active ">
                        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" data-interval="1500">
                            <div class="carousel-inner">
                                <% @banners.each do |banner| %>
                                    <div class="carousel-item <%= "active" if banner == @banners.first %>">
                                        <div class="col-sm-6 ">
                                            <h1><span>E</span>-SHOP</h1>
                                            <h2>Free Delivery above $500</h2>
                                            <p>Avail the offer now, it is availble for limited period of time , sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                                        </div>
                                        <div class="col-sm-6 ">
                                            <%= image_tag url_for(banner.image),height:"250"%>
                                        </div>
                                    </div>
                                <% end %>
                            </div>
                            <a class="left control-carousel hidden-xs" data-slide="prev" data-target="#carouselExampleControls">
                                <i class="fa fa-angle-left" ></i>
                            </a>
                            <a class="right control-carousel hidden-xs" data-slide="next" data-target="#carouselExampleControls">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section><!--/slider-->

app/views/shared/_features.html.erb
<h2 class="title text-center">All Items</h2>
<% @products.each do |product| %>
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                     <%= image_tag url_for(product.product_images.first), height:"200" if product.product_images.first %>
                    <h2>$<%= product.price %></h2>
                    <p><%= product.short_description %></p>
                    <a href="<%= line_items_path(product_id: product) %>" data-method="post" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart" data-remote="true"></i>Add to cart</a>
                </div>
                <div class="product-overlay">
                    <div class="overlay-content">
                        <h2>$<%= product.price %></h2>
                        <p><%= product.short_description %></p>
                        <a href="<%= line_items_path(product_id: product) %>" data-method="post" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart" data-remote="true"></i>Add to cart</a>
                    </div>
                </div>
            </div>
            <div class="choose">
                <ul class="nav nav-pills justify-content-center">
                    <li><a href="<%= wishlists_path(product_id: product) %>" data-method="post" data-remote="true" ><i class="fa fa-plus-square"></i>Add to wishlist |</a></li>
                    <li><a href="<%= product_path(product) %>"><i class="fa fa-plus-square"></i>Show the product</a></li>
                </ul>
            </div>
        </div>
    </div>
<% end %>

app/views/shared/_product.html.erb
 <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-6  p-5 mt-5">
        <div class="card" style="opacity:1; border:none">
          <div class="card-body text-center" style="background-color:#fae4bb;">
            <div class="my-5">
              <div class="site-heading">
                  <% (@product.product_images).each do |image| %>
                    <%=image_tag image.image ,style:"width:300px;height:300;display:center;"  %>
                  <% end %>
              </div>
              <div class="site-heading">
                <h1><%= @product.name.capitalize %></h1>
                <span class="subheading"><%= @product.short_description.capitalize %></span>
                <p><h5 class="card-title"><span class="mb-0">Price: $</span><%= @product.price %></h5></p>
              </div>
              <br>
              <div class="site-heading">
                <a href="<%= products_path %>" class="btn btn-primary" style="background-color:#477bb3 ">Back to Product list</a>
                <a href="<%= line_items_path(product_id: @product.id) %>" class="btn btn-warning" data-method="post" style="background-color:#f7b807">Add to Cart <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/shared/_sidebar.html.erb
<h2>Category</h2>
<div class="panel-group category-products" id="accordian"><!--category-productsr-->
	<div class="panel panel-default">
		<div class="panel-heading">
			<h2 class="single-widget">
				<ul class="nav-stacked">
                    <% Category.all.each do |category| %>
                        <li>
                            <%= link_to category.name.capitalize, category_path(category) %>
                        </li><br>
                    <% end %>
                </ul>
			</h2>
		</div>
		<%# <div id="sportswear" class="panel-collapse collapse">
			<div class="panel-body">
				<ul>
					<li><a href="">Nike </a></li>
					<li><a href="">Under Armour </a></li>
					<li><a href="">Adidas </a></li>
					<li><a href="">Puma</a></li>
					<li><a href="">ASICS </a></li>
				</ul>
			</div>
		</div> %>
	</div>
	<%# <div class="panel panel-default">
		<div class="panel-heading">
			<h4 class="panel-title">
				<a data-toggle="collapse" data-parent="#accordian" href="#mens">
					<span class="badge pull-right"><i class="fa fa-plus"></i></span>
					Mens
				</a>
			</h4>
		</div>
		<div id="mens" class="panel-collapse collapse">
			<div class="panel-body">
				<ul>
					<li><a href="">Fendi</a></li>
					<li><a href="">Guess</a></li>
					<li><a href="">Valentino</a></li>
					<li><a href="">Dior</a></li>
					<li><a href="">Versace</a></li>
					<li><a href="">Armani</a></li>
					<li><a href="">Prada</a></li>
					<li><a href="">Dolce and Gabbana</a></li>
					<li><a href="">Chanel</a></li>
					<li><a href="">Gucci</a></li>
				</ul>
			</div>
		</div>
	</div>
	
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 class="panel-title">
				<a data-toggle="collapse" data-parent="#accordian" href="#womens">
					<span class="badge pull-right"><i class="fa fa-plus"></i></span>
					Womens
				</a>
			</h4>
		</div>
		<div id="womens" class="panel-collapse collapse">
			<div class="panel-body">
				<ul>
					<li><a href="">Fendi</a></li>
					<li><a href="">Guess</a></li>
					<li><a href="">Valentino</a></li>
					<li><a href="">Dior</a></li>
					<li><a href="">Versace</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 class="panel-title"><a href="#">Kids</a></h4>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 class="panel-title"><a href="#">Fashion</a></h4>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 class="panel-title"><a href="#">Households</a></h4>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 class="panel-title"><a href="#">Interiors</a></h4>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 class="panel-title"><a href="#">Clothing</a></h4>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 class="panel-title"><a href="#">Bags</a></h4>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 class="panel-title"><a href="#">Shoes</a></h4>
		</div>
	</div> %>
</div><!--/category-products-->