config/routes.rb
Rails.application.routes.draw do

 
  root 'products#index'
  get 'home/index', to: 'home#index'
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  resources :orders, :line_items, :carts, :coupons, :addresses, :wishlists

  post 'check_coupon_code', to: 'coupons#check_coupon_code'
  delete 'remove_coupon', to: 'coupons#remove_coupon'
  delete 'remove_from_wishlist', to: 'wishlists#remove_from_wishlist'
  delete 'remove_product_from_order', to: 'orders#remove_product_from_order'
  get 'get_deleted_products', to: 'orders#get_deleted_products'


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :products, only: [:index, :show]
  #   resources :product_images
  # end
  resources :categories, only: [:show]
  resources :webhooks, only: [:create]
  resources :charges, only: [:new, :create]
  resources :paypals, only: [:new, :create]
  resources :track_orders,only: [:new, :create, :show]
  resources :contacts, only: [:index, :create]
  resources :refunds


  resources :newsletters, only: [:index, :create, :destroy]
  get '/newsletters/subscribe', to: 'newsletters#subscribe'
  get '/newsletters/unsubscribe', to: 'newsletters#unsubscribe'

end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_product(product_id)
        current_item = line_items.find_by(product_id: product_id)
        if current_item
            current_item.quantity += 1
        else
            current_item = line_items.build(product_id: product_id)
        end
        current_item
    end

    def total
        line_items.to_a.sum {|item| item.total}
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # include CurrentCart
  before_action :set_cart, only: %i[ show edit update destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
    @coupon = Coupon.new
    if @cart.total < 500
      @shipping_cost = 50
    else
      @shipping_cost = 0
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        # format.html { redirect_to root_url, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to root_url, notice: "Your Cart Is Currently Empty" }
      format.json { head :no_content }
    end
  end

  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
    
    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_url, notice: "Invalid Cart"
    end
end

app/helpers/carts_helper.rb
module CartsHelper
    # def get_addresses
    #     ["A-304 Golden Park", "C-401 Diamond Tower"]
    # end

    def get_user_addresses
        addresses = Array.new
        if user_signed_in?
            current_user.addresses.each do |address|             
                addresses << ["#{address.address_1}, #{address.address_2}, #{address.city}, #{address.state}", address.id]
            end
        end
        addresses
    end
end

app/views/carts/_cart.html.erb
<h2>Your cart</h2>
<table>
    <%= render(cart.line_items) %>
    <tr class="total_line">
        <td colspan="2">Total</td>
        <td class="total_cell"><%= cart.total %></td>
    </tr>
</table>

<%= button_to "Checkout", new_order_path, method: :get %>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/show.html.erb
<div class="container text-center">
	<p>
		<% if @cart.line_items.present? %>
			<h2 class="fw-normal mb-0 text-black">Your Cart <%=current_user.name.split(" ").first %></h2>
		<% else %>
			<h2 class="fw-normal mb-0 text-black">Your Cart is Empty <%=current_user.name.split(" ").first %></h2>
		<% end %>
	</p>
</div>


<section id="cart_items" class="container">
	<div class="table-responsive cart_info">
		<table class="table table-condensed">
			<thead>
				<tr class="cart_menu">
					<td class="image">Item</td>
					<td class="description">Description</td>
					<td class="price">Price</td>
					<td class="quantity">Quantity</td>
					<td class="total">Total</td>
					<td class="total">Remove</td>
				</tr>
			</thead>
			<tbody>
				<% @cart.line_items.each do |item|%>
					<tr>
						<td class="cart_price">
							<%= image_tag (item.product.product_images.first), width:"100",class:"img-responsive" if item.product.product_images.first  %>
						</td>
						<td class="cart_description py-5">
							<p class="lead fw-normal mb-2"><%= item.product.name.capitalize %></p>
							<p><span class="text-muted">desc.:</span><%= item.product.short_description.capitalize%></p>
						</td>
						<td class="cart_price py-5">
							<p>$<%= item.product.price %></p>
						</td>

						<td class="cart_price px-5 py-5">
							<p> <%= item.quantity %></p>
						</td>
						<%#	<td class="cart_quantity">
								<div class="cart_quantity_button">
									<a class="cart_quantity_up" href=""> + </a>
									<input class="cart_quantity_input" type="text" name="quantity" value="1" autocomplete="off" size="2">
									<a class="cart_quantity_down" href=""><%= item.quantity %> <%#</a>
								</div>
								<h5 class="cart_price"></h5>
							</td>%>
						<td class="cart_total py-5">
							<p class="cart_total_price">$<%= item.total%></p>
						</td>
						<td class="cart_total px-5 py-5">
							<%= link_to '', item, method: :delete, data: {confirm: 'You sure?'}, class:"fa fa-trash fa-lg text-danger" %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</section> <!--/#cart_items-->

<section id="do_action">
	<div class="container">
		<div class="heading">
			<h3>What would you like to do next?</h3>
			<p>Choose if you have a discount code or coupons you want to use.</p>
		</div>
		<div class="row">
			<div class="col-sm-7">
				<div class="total_area">
					<ul>
						<div id="coupon-notice">
						</div>
					</ul>
					<ul>
						<li style="font-size:15px">Cart Sub Total<span>$<%= @cart.total%></span></li>
						<li id="new-coupon">
							<%= form_for @coupon, method: :post,  url: check_coupon_code_path, remote: true do |f| %>
								<%= f.hidden_field :total, :value => @cart.total %>
								<%= f.hidden_field :shipping_cost, :value => @shipping_cost %>
								<div class="d-flex justify-content-center">
									<%= f.text_field :code, :placeholder => "Enter your coupon",class:"form-control form-control-lg text-center" %>
									<span id="coupon-buttons" ><%= f.submit "Apply", class:"btn btn-outline-warning btn-lg ms-3 mx-2" %></span>
								</div>
							<% end %>
						</li>
						<li>
							<% if @shipping_cost == 0 %>
							<p style="font-size:15px">Shipping Cost <span>$50</span></p>
							<% end %>
							<p style="font-size:15px">Shipping Discount <span>- $50</span></p>
						</li>
						<li>
							<% if @shipping_cost == 0 %>
							<p style="font-size:15px">Total <span>$<%= @cart.total = @cart.total + @shipping_cost + 50 %></span></p>
							<% end %>
							<div id="coupon-discount">
								<!-- This is for code -->
							</div>

							<p style="font-size:15px">Discounted Total <span id="cart-total">$<%= @cart.total = @cart.total + @shipping_cost%></span></p>
						</li>
					</ul>
					<div id= "cart-total-form" class="" >
						<%= form_with  url: new_order_path, method: :get do |f| %>
							<%= f.hidden_field :total, :value => @cart.total+@shipping_cost %>
							<%= f.hidden_field :address_id, :value => 0 %>
							<%= f.hidden_field :coupon_id, :value => 0 %>
							<%= f.submit "Checkout", class:"btn btn-outline-success btn-lg mx-4 ", style:"font-size:18px" %>
						<% end %>
					</div>
				</div>
			</div>
			<div class="col-sm-5">
				<div class="total_area">
					<div id="new-address-form">
					<!--address selection-->
						<div class="select-class mx-3">
							<%= select_tag :temp_address, options_for_select(get_user_addresses),
							prompt: "Please Select Address",  id:"address-select", style:"font-size:13px"%>
						</div><br>
							<!--add address -->
						<%= link_to "Add new address", new_address_path, class:"btn btn-outline-success btn-lg ms-3 mx-4", style:"font-size:15px", remote: true %>
					</div>
				</div>
			</div>
		</div>
	</div>
</section><!--/#do_action-->

  <!--for adding address id into checkout form-->
<script>
  $("#address-select").change(function() {
  var id = $( "#address-select option:selected").val();
  $("#address_id").val(id);
  });
</script>