config/routes.rb
Rails.application.routes.draw do

 
  root 'products#index'
  get 'home/index', to: 'home#index'
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  resources :orders, :line_items, :carts, :coupons, :addresses, :wishlists

  post 'check_coupon_code', to: 'coupons#check_coupon_code'
  delete 'remove_coupon', to: 'coupons#remove_coupon'
  delete 'remove_from_wishlist', to: 'wishlists#remove_from_wishlist'
  delete 'remove_product_from_order', to: 'orders#remove_product_from_order'
  get 'get_deleted_products', to: 'orders#get_deleted_products'


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :products, only: [:index, :show]
  #   resources :product_images
  # end
  resources :categories, only: [:show]
  resources :webhooks, only: [:create]
  resources :charges, only: [:new, :create]
  resources :paypals, only: [:new, :create]
  resources :track_orders,only: [:new, :create, :show]
  resources :contacts, only: [:index, :create]
  resources :refunds


  resources :newsletters, only: [:index, :create, :destroy]
  get '/newsletters/subscribe', to: 'newsletters#subscribe'
  get '/newsletters/unsubscribe', to: 'newsletters#unsubscribe'

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:new, :create]
  rescue_from Stripe::CardError, with: :catch_exception

  def new
    @total = params[:total]
    @pay_type = params[:pay_type]
    @address_id = params[:address_id]
    @coupon_id = params[:coupon_id]
  end

  def create

    @order = Order.new
    pay_type = params[:pay_type]
    address_id = params[:address_id].to_i
    @total = params[:total]
    coupon_id = params[:coupon_id]
    @amount = (@total*100).to_i

    # @order.pay_type = params
    Stripe.api_key = Rails.application.credentials.dig(:stripe, :stripe_secret_key)

    # byebug
    payment_intent = Stripe::PaymentIntent.create(
      :customer => current_user.stripe_customer_id,
      :amount => @amount*100,
      :description => current_user.email ,
      :currency => 'inr',
      # :payment_method_options => { card: {request_three_d_secure: :null}},
      :payment_method_data => { type: 'card',
       card: {token: params[:stripeToken]},}
    )

    payment_confirm = Stripe::PaymentIntent.confirm(
      payment_intent.id,
      {payment_method: 'pm_card_visa'},
    )

    # byebug
    @order.pay_type = pay_type
    unless coupon_id == "0"
      @order.coupon_id = coupon_id
    end
    @order.address_id = address_id
    @order.total = params[:total].to_i
    @order.user_id = current_user.id
    @order.stripe_payment_id = payment_intent.id


    puts @order.inspect

    respond_to do |format|
      if @order.save
        add_from_cart_to_order_details(@cart, @order)
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil

        format.html { redirect_to root_url, notice: "Your Order Has Been Placed.Thank you For Shopping With Us !!" }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def catch_exception(exception)
    flash[:error] = exception.message
  end


end


# :payment_method_data => { type: 'card',
#   card: {token: params[:stripeToken]},

# payment_intent = Stripe::PaymentIntent.create(:customer => current_user.stripe_customer_id,:amount => @amount*100,:description => current_user.email,:currency => 'inr',:payment_method_data => { type: 'card', card: {token: params[:stripeToken]}},)
  # confirmation_method: 'manual',
  # :confirm => true,

# payment_confirm = Stripe::PaymentIntent.confirm(payment_intent.id,{payment_method: 'pm_card_threeDSecureOptional'},)

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%=@cart.total%></strong>!</h2>

app/views/charges/create.js.erb
var stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :stripe_secret_key) %>");

var checkoutButton = document.getElementById('checkout-button');

stripe.redirectToCheckout({
	sessionId: '<%= @session.id %>'
	}).then(function(result){
	});

app/views/charges/new.html.erb
<section class="login-block">
    <div class="container-fluid">
      <div class="card justify-content-center">
        <div id="cart_items" class="row justify-content-center mb-5">
          <div class="col col-sm-8">
            <table class="table table-responsive">
              <thead>
                <tr>
                  <th>Item</th>
                  <th>Description</th>
                  <th>Quantity</th>
                </tr>
              </thead>
              <tbody>
                <% @cart.line_items.each do |item|%>
                  <tr>
                    <td >
                      <%= image_tag (item.product.product_images.first), width:"100",class:"img-responsive" if item.product.product_images.first  %>
                    </td>
                    <td >
                      <p class="lead fw-normal mb-2"><%= item.product.name.capitalize %></p>
                      <p><span class="text-muted">desc.:</span><%= item.product.short_description.capitalize%></p>
                    </td>
                    <td >
                      <p> <%= item.quantity %></p>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="row justify-content-center mb-5">
          <div class="col col-sm-4">
              <p class="px-4 py-0 m-0" >Your Billing/Shipping Address:-</p> <span style="font-size:1.5rem;color:#874d2b;"><%= "#{current_user.addresses.find(@address_id).address_1.capitalize},
                  #{current_user.addresses.find(@address_id).address_2},  #{current_user.addresses.find(@address_id).city},
                  #{current_user.addresses.find(@address_id).state}, #{current_user.addresses.find(@address_id).zipcode}. "%></span>
          </div>
          <div class="col col-sm-4">
              <%= form_tag charges_path do %>
              <input type="hidden" id="total" name="total" value="<%=@total%>" >
              <input type="hidden" id="address_id" name="address_id" value="<%=@address_id%>" >
              <input type="hidden" id="pay_type" name="pay_type" value="<%=@pay_type%>" >
              <input type="hidden" id="coupon_id" name="coupon_id" value="<%=@coupon_id%>" >
              <article>
                <% if flash[:error].present? %>
                <div id="error_explanation">
                  <p><%= flash[:error] %></p>
                </div>
                <% end %>
                <label class="amount">
                <span>Amount: $<%= @total %></span>
                </label>
              </article>

              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.application.credentials.dig(:stripe, :stripe_public_key) %>"
                data-description="Enter Card Details"
                data-amount="<%= (@total.to_i*100) %>"
                data-currency="usd"
                data-locale="auto"></script>
              <% end %>
          </div>
        </div>
      </div>
    </div>
</section>